리뷰, 코스 페이지 제작 / 마이페이지 수정
leave-assistant/TourMate pull request #14
Opened 2023-09-24 16:11 UTC by jisujisujisu

마이페이지 빼먹은거랑 수정해야 할 내용 수정했고요
마이페이지 하단에 만들어놓은 리뷰버튼이랑 이전코스버튼을 간단하게만 페이지 하나씩 만들어서 연결한 후 같이 넣어놨는데, 혹시 문제 생기거나 잘못 만든거라면 알려주세요...

2023-09-24 17:18 UTC, Anhagu requested changes
전체적으로 잘 만드셨네요^^
MyPageWrapper랑 MenuBar는 없어야 해서 삭제 혹은 주석처리 해주시면 좋을거 같구요
중앙정렬하실때 justify-content등과 같이 flex 속성 사용해서 만들면 수정&관리에 좋을거 같아요!
코스내역, 리뷰 버튼은 속성 사용하셔서 잘 만드셨어요~ 굿

2023-09-24 17:18 UTC, Anhagu commented on src/pages/MyPage/Course.tsx
> +      <MenuBar></MenuBar>
코드만 보자면
```
<MenuBar/>
```
로 작성하면 더 좋을 거 같아요.

2023-09-24 17:18 UTC, Anhagu commented on src/pages/MyPage/Course.tsx
> +    <MyPageWrapper>
컨텐츠를 보여주는 자식 컴포넌트만 만들면 되서
```
<MyPageWrapper>
<MenuBar>
```
는 삭제해주시면 됩니다.

2023-09-24 17:18 UTC, Anhagu commented on src/pages/MyPage/MyPage.tsx
> +  margin: 35px 0px 0px 10px;
Margin값으로 중앙 정렬하기 보다는
```
display:flex;
justify-content: center;
```
로 중앙 정렬하시는게 정확히 중앙정렬하시는데 편하시고 좋을거에요.

2023-09-24 17:18 UTC, Anhagu commented on src/pages/MyPage/MyPage.tsx
> -  margin-top: 25px;
아래의 질문요소도 justify-content:center가 더 편할겁니다.

2023-09-25 06:47 UTC, asitwas729 commented
수고하셨습니당

2023-09-27 03:23 UTC, closed without merging